/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2Etz9fT2lxz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function SignIn() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-[#f5f5f5] px-4 py-12 sm:px-6 lg:px-8">
      <div className="w-full max-w-md space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-[#333333]">Sign in to your account</h2>
          <p className="mt-2 text-center text-sm text-[#666666]">
            Or{" "}
            <Link href="#" className="font-medium text-[#4a90e2] hover:text-[#3b7dbd]" prefetch={false}>
              sign up for a new account
            </Link>
          </p>
        </div>
        <form className="space-y-6" action="#" method="POST">
          <div>
            <Label htmlFor="email" className="sr-only">
              Email address
            </Label>
            <Input
              id="email"
              name="email"
              type="email"
              autoComplete="email"
              required
              placeholder="Email address"
              className="relative block w-full appearance-none rounded-md border border-[#d8d8d8] px-3 py-2 text-[#333333] placeholder-[#999999] focus:z-10 focus:border-[#4a90e2] focus:outline-none focus:ring-[#4a90e2] sm:text-sm"
            />
          </div>
          <div>
            <Label htmlFor="password" className="sr-only">
              Password
            </Label>
            <Input
              id="password"
              name="password"
              type="password"
              autoComplete="current-password"
              required
              placeholder="Password"
              className="relative block w-full appearance-none rounded-md border border-[#d8d8d8] px-3 py-2 text-[#333333] placeholder-[#999999] focus:z-10 focus:border-[#4a90e2] focus:outline-none focus:ring-[#4a90e2] sm:text-sm"
            />
          </div>
          <div>
            <Select  className="w-full">
              <SelectTrigger className="relative block w-full appearance-none rounded-md border border-[#d8d8d8] px-3 py-2 text-[#333333] placeholder-[#999999] focus:z-10 focus:border-[#4a90e2] focus:outline-none focus:ring-[#4a90e2] sm:text-sm">
                <SelectValue placeholder="Select role" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="patient">Patient</SelectItem>
                <SelectItem value="doctor">Doctor</SelectItem>
                <SelectItem value="caregiver">Caregiver</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Checkbox id="remember-me" name="remember-me" />
              <Label htmlFor="remember-me" className="ml-2 block text-sm text-[#666666]">
                Remember me
              </Label>
            </div>
            <div className="text-sm">
              <Link href="#" className="font-medium text-[#4a90e2] hover:text-[#3b7dbd]" prefetch={false}>
                Forgot your password?
              </Link>
            </div>
          </div>
          <div>
            <Button
              type="submit"
              className="relative flex w-full justify-center rounded-md bg-[#4a90e2] px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#3b7dbd] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#4a90e2]"
            >
              Sign in
            </Button>
          </div>
        </form>
        <div className="flex items-center justify-center space-x-4">
          <Button
            variant="outline"
            className="flex items-center justify-center bg-white text-[#666666] hover:bg-[#f0f0f0] transition-colors"
          >
            <ChromeIcon className="h-5 w-5 mr-2" />
            Sign in with Google
          </Button>
          <Button
            variant="outline"
            className="flex items-center justify-center bg-white text-[#666666] hover:bg-[#f0f0f0] transition-colors"
          >
            <FacebookIcon className="h-5 w-5 mr-2" />
            Sign in with Facebook
          </Button>
        </div>
      </div>
    </div>
  )
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}
